// Generated by Microsoft Cadl

// Requires use of the Azure Identity library
import type { TokenCredential } from "@azure/identity";

interface GetSecretOptions {
  version?: string;
}

interface SecretValue {
  value?: string;
  id?: string;
  contentType?: string;
  tags?: { [k: string]: string };
  kid?: string;
  managed?: boolean;
}

export async function getSecret(
  baseUrl: URL,
  credential: TokenCredential,
  name: string,
  apiVersion: "7.3",
  options: GetSecretOptions = {}
): Promise<SecretValue> {
  // GET /secrets/{name}/{version}
  const path = `/secrets/${name}/${options.version ?? ""}`;
  const query = `?api-version=${apiVersion}`;
  const resource = new URL(path + query, baseUrl).toString();

  const authorization = await credential.getToken(
    "https://vault.azure.net/.default"
  );

  const init = {
    method: "GET",
    headers: {
      Authorization: `Bearer ${authorization?.token}`,
      "Content-Type": "application/json",
    },
  };

  const res = await fetch(resource, init);

  return res.json();
}

// Inline fetch polyfill?
const fetch =
  typeof globalThis.fetch === "undefined"
    ? (await import("node-fetch")).default
    : globalThis.fetch;
