// Generated by Microsoft Cadl

// Requires use of the Azure Identity library
import type { TokenCredential } from "@azure/identity";

interface SetSecretRequestBody {
  value: string;
  contentType?: string;
  tags?: { [k: string]: string };
}

export async function setSecret(
  baseUrl: URL,
  credential: TokenCredential,
  name: string,
  apiVersion: "7.3",
  body: SetSecretRequestBody
): Promise<Response> {
  // PUT /secrets/{name}
  const path = `/secrets/${name}`;
  const query = `?api-version=${apiVersion}`;
  const resource = new URL(path + query, baseUrl).toString();

  const authorization = await credential.getToken(
    "https://graph.microsoft.com/.default"
  );

  const init: RequestInit = {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${authorization?.token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  };

  const res = await fetch(resource, init);

  return res;
}
