// Generated by Microsoft Cadl
export async function setSecret(baseUrl, credential, name, apiVersion, body) {
    // PUT /secrets/{name}
    const path = `/secrets/${name}`;
    const query = `?api-version=${apiVersion}`;
    const resource = new URL(path + query, baseUrl).toString();
    const authorization = await credential.getToken("https://graph.microsoft.com/.default");
    const init = {
        method: "PUT",
        headers: {
            Authorization: `Bearer ${authorization?.token}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify(body),
    };
    const res = await fetch(resource, init);
    return res;
}
//# sourceMappingURL=setSecret.js.map